version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.14.4"
      ONLINE_MODE: "FALSE"
      VIEW_DISTANCE: "10"
      MODE: "creative"
      MEMORY: "2G"
      NETWORK_COMPRESSION_THRESHOLD: "-1"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./data:/data
