[package]
name = "brine_net"
version = "0.0.0"
edition = "2021"

[dependencies]
async-channel = "1.6"
async-codec = "0.4"
async-net = "1.6"
bevy = { version = "0.6", default-features = false }
byteorder = "1"
crossbeam-channel = "0.5"
futures = "0.3"
futures-lite = "1"
thiserror = "1"
