[package]
name = "brine_asset"
version = "0.0.0"
edition = "2021"

[dependencies]
glam = "0.20"
indexmap = "1.8"
rayon = "1.5"
smallvec = "1"
tracing = "0.1"

brine_data = { path = "../brine_data" }
minecraft-assets = { path = "../minecraft-assets-rs" }
