[package]
name = "brine_proto_backend"
version = "0.0.0"
edition = "2021"

[dependencies]
bevy = "0.6.0"
minecraft-protocol = { git = "https://github.com/bgr360/minecraft-protocol", branch = "my-fork" }
pretty-hex = "0.2"

brine_net = { path = "../brine_net" }
brine_proto = { path = "../brine_proto" }

[dev-dependencies]
assert_matches = "1"
async-std = { version = "1", features = ["attributes"] }
async-codec = "0.4"
futures = "0.3"
uuid = "0.7" # should be 0.8 to match other crates, but minecraft-proto is behind
